### ISSUE TITLE
Client has quit the connection (state=READY)

### ISSUE THREAD

**Issue by mrsuccessful-cyber** [spezifisch/docker-dovecot-mettmail#1]
Hello there,
I'm so glad I found this!
Detailed documentation makes it easy for a noob like me to install it.
In Dovecot, however, I'm missing some emails:

Nov 15 04:11:05 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:06 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:11:14 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:14 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:11:22 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:23 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:11:31 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:31 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:11:40 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:41 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:11:50 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:11:50 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:12:01 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:12:02 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:12:16 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:12:16 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)
Nov 15 04:12:36 lmtp(59): Info: Connect from 172.23.0.11
Nov 15 04:12:37 lmtp(59): Info: Disconnect from 172.23.0.11: Client has quit the connection (state=READY)

**While in mettmail container logs I see:**

2022-11-15 04:11:35.617 | INFO     | mettmail.mettmail_loop:mettmail_loop:33 - connecting
2022-11-15 04:11:37.874 | INFO     | mettmail.fetch_imap:connect:116 - connected to imap.gmail.com
2022-11-15 04:11:37.875 | INFO     | mettmail.mettmail_loop:mettmail_loop:45 - initial fetch
2022-11-15 04:11:40.749 | ERROR    | mettmail.mettmail_loop:mettmail_loop:56 - fetcher error
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/mettmail/mettmail_loop.py", line 46, in mettmail_loop
    await fetcher.fetch_deliver_unflagged_messages()
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 247, in fetch_deliver_unflagged_messages
    await self.fetch_deliver_message(uid)  # raises MettmailExceptions on failure
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 283, in fetch_deliver_message
    raise MettmailFetchUnexpectedResponse(f"expected completed string, got response: {response}")
mettmail.exceptions.MettmailFetchUnexpectedResponse: expected completed string, got response: Response(result='OK', lines=[b'1 FETCH (UID 61339 RFC822.SIZE 5704 FLAGS (\\Seen) BODY[] {5704}', bytearray(b'Delivered-To: xxxxxxxxxxxxxxxxx@gmail.com\r\n"EMAIL-BODY", b'Success'])
2022-11-15 04:11:45.528 | INFO     | mettmail.mettmail_loop:mettmail_loop:33 - connecting
2022-11-15 04:11:47.784 | INFO     | mettmail.fetch_imap:connect:116 - connected to imap.gmail.com
2022-11-15 04:11:47.785 | INFO     | mettmail.mettmail_loop:mettmail_loop:45 - initial fetch
2022-11-15 04:11:50.629 | ERROR    | mettmail.mettmail_loop:mettmail_loop:56 - fetcher error
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/mettmail/mettmail_loop.py", line 46, in mettmail_loop
    await fetcher.fetch_deliver_unflagged_messages()
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 247, in fetch_deliver_unflagged_messages
    await self.fetch_deliver_message(uid)  # raises MettmailExceptions on failure
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 283, in fetch_deliver_message
    raise MettmailFetchUnexpectedResponse(f"expected completed string, got response: {response}")
mettmail.exceptions.MettmailFetchUnexpectedResponse: expected completed string, got response: Response(result='OK', lines=[b'1 FETCH (UID 61339 RFC822.SIZE 5704 FLAGS (\\Seen) BODY[] {5704}', bytearray(b'Delivered-To: xxxxxxxxxxxxxxxxx@gmail.com\r\n"EMAIL-BODY", b'Success'])
2022-11-15 04:11:57.109 | INFO     | mettmail.mettmail_loop:mettmail_loop:33 - connecting
2022-11-15 04:11:58.806 | INFO     | mettmail.fetch_imap:connect:116 - connected to imap.gmail.com
2022-11-15 04:11:58.807 | INFO     | mettmail.mettmail_loop:mettmail_loop:45 - initial fetch
2022-11-15 04:12:01.793 | ERROR    | mettmail.mettmail_loop:mettmail_loop:56 - fetcher error
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/mettmail/mettmail_loop.py", line 46, in mettmail_loop
    await fetcher.fetch_deliver_unflagged_messages()
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 247, in fetch_deliver_unflagged_messages
    await self.fetch_deliver_message(uid)  # raises MettmailExceptions on failure
mettmail.exceptions.MettmailFetchUnexpectedResponse: expected completed string, got response: Response(result='OK', lines=[b'1 FETCH (UID 61339 RFC822.SIZE 5704 FLAGS (\\Seen) BODY[] {5704}', bytearray(b'Delivered-To: xxxxxxxxxxxxxxxxx@gmail.com\r\n"EMAIL-BODY", b'Success'])
2022-11-15 04:12:11.316 | INFO     | mettmail.mettmail_loop:mettmail_loop:33 - connecting
2022-11-15 04:12:13.529 | INFO     | mettmail.fetch_imap:connect:116 - connected to imap.gmail.com
2022-11-15 04:12:13.529 | INFO     | mettmail.mettmail_loop:mettmail_loop:45 - initial fetch
2022-11-15 04:12:16.409 | ERROR    | mettmail.mettmail_loop:mettmail_loop:56 - fetcher error
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/mettmail/mettmail_loop.py", line 46, in mettmail_loop
    await fetcher.fetch_deliver_unflagged_messages()
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 247, in fetch_deliver_unflagged_messages
    await self.fetch_deliver_message(uid)  # raises MettmailExceptions on failure
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 283, in fetch_deliver_message
    raise MettmailFetchUnexpectedResponse(f"expected completed string, got response: {response}")
mettmail.exceptions.MettmailFetchUnexpectedResponse: expected completed string, got response: Response(result='OK', lines=[b'1 FETCH (UID 61339 RFC822.SIZE 5704 FLAGS (\\Seen) BODY[] {5704}', bytearray(b'Delivered-To: xxxxxxxxxxxxxxxxx@gmail.com\r\n"EMAIL-BODY", b'Success'])
2022-11-15 04:12:32.257 | INFO     | mettmail.mettmail_loop:mettmail_loop:33 - connecting
2022-11-15 04:12:33.937 | INFO     | mettmail.fetch_imap:connect:116 - connected to imap.gmail.com
2022-11-15 04:12:33.938 | INFO     | mettmail.mettmail_loop:mettmail_loop:45 - initial fetch
2022-11-15 04:12:36.743 | ERROR    | mettmail.mettmail_loop:mettmail_loop:56 - fetcher error
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/mettmail/mettmail_loop.py", line 46, in mettmail_loop
    await fetcher.fetch_deliver_unflagged_messages()
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 247, in fetch_deliver_unflagged_messages
    await self.fetch_deliver_message(uid)  # raises MettmailExceptions on failure
  File "/app/.venv/lib/python3.9/site-packages/mettmail/fetch_imap.py", line 283, in fetch_deliver_message
    raise MettmailFetchUnexpectedResponse(f"expected completed string, got response: {response}")

**Comment by mrsuccessful-cyber** [comment]
Nov 15 08:13:31 master: Info: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp, sieve, lmtp, sieve
Nov 15 08:19:10 imap-login: Info: Login: user=<business>, method=PLAIN, rip=192.168.2.100, lip=172.23.0.6, mpid=17, TLS, session=</ZenE3vtNSbAqAJk>
Nov 15 08:19:10 imap-login: Info: Login: user=<business>, method=PLAIN, rip=192.168.2.100, lip=172.23.0.6, mpid=19, TLS, session=<neaoE3vtNibAqAJk>
Nov 15 08:19:10 imap-login: Info: Login: user=<personal>, method=PLAIN, rip=192.168.2.100, lip=172.23.0.6, mpid=21, TLS, session=<yY2tE3vtOCbAqAJk>
Nov 15 08:19:58 lmtp(22): Info: Connect from 172.23.0.5
Nov 15 08:19:58 lmtp(23): Info: Connect from 172.23.0.3
Nov 15 08:19:58 lmtp(22): Info: Disconnect from 172.23.0.5: Client has quit the connection (state=READY)
Nov 15 08:19:58 lmtp(22): Info: Connect from 172.23.0.10
Nov 15 08:19:58 lmtp(24): Info: Connect from 172.23.0.9
Nov 15 08:19:58 lmtp(business)<23><nI/COHYac2MXAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:19:59 lmtp(25): Info: Connect from 172.23.0.8
Nov 15 08:19:59 lmtp(23): Info: Disconnect from 172.23.0.3: Client has quit the connection (state=READY)
Nov 15 08:19:59 lmtp(24): Info: Disconnect from 172.23.0.9: Client has quit the connection (state=READY)
Nov 15 08:19:59 lmtp(22): Info: Disconnect from 172.23.0.10: Client has quit the connection (state=READY)
Nov 15 08:19:59 lmtp(25): Info: Disconnect from 172.23.0.8: Client has quit the connection (state=READY)
Nov 15 08:20:03 lmtp(22): Info: Connect from 172.23.0.5
Nov 15 08:20:03 lmtp(business)<22><GxEDGnsac2MWAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:20:03 lmtp(22): Info: Disconnect from 172.23.0.5: Client has quit the connection (state=READY)
Nov 15 08:20:03 lmtp(24): Info: Connect from 172.23.0.8
Nov 15 08:20:04 lmtp(business)<24><Lk8OAHwac2MYAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:20:04 lmtp(22): Info: Connect from 172.23.0.9
Nov 15 08:20:04 lmtp(24): Info: Disconnect from 172.23.0.8: Client has quit the connection (state=READY)
Nov 15 08:20:04 lmtp(business)<22><wO4IDHwac2MWAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:20:04 lmtp(22): Info: Disconnect from 172.23.0.9: Client has quit the connection (state=READY)
Nov 15 08:20:08 lmtp(22): Info: Connect from 172.23.0.4
Nov 15 08:20:08 lmtp(business)<22><wLP7NYAac2MWAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:20:09 lmtp(22): Info: Disconnect from 172.23.0.4: Client has quit the connection (state=READY)
Nov 15 08:20:12 lmtp(25): Info: Connect from 172.23.0.2
Nov 15 08:20:12 lmtp(business)<25><85szD4Qac2MZAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:20:12 lmtp(25): Info: Disconnect from 172.23.0.2: Client has quit the connection (state=READY)
Nov 15 08:20:41 imap-login: Info: Login: user=<business>, method=PLAIN, rip=192.168.2.100, lip=172.23.0.6, mpid=28, TLS, session=<PpAhGXvtVybAqAJk>
Nov 15 08:20:41 imap-login: Info: Login: user=<personal>, method=PLAIN, rip=192.168.2.100, lip=172.23.0.6, mpid=29, TLS, session=<GtwhGXvtWCbAqAJk>
Nov 15 08:21:38 lmtp(30): Info: Connect from 172.23.0.10
Nov 15 08:21:39 lmtp(business)<30><OCSLO9oac2MeAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218855C1723CC74DEC486456A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:21:39 lmtp(30): Info: Disconnect from 172.23.0.10: Client has quit the connection (state=READY)
Nov 15 08:22:42 lmtp(31): Info: Connect from 172.23.0.9
Nov 15 08:22:43 lmtp(31): Info: Disconnect from 172.23.0.9: Client has quit the connection (state=READY)
Nov 15 08:22:47 lmtp(31): Info: Connect from 172.23.0.9
Nov 15 08:22:48 lmtp(business)<31><UEWVEyAbc2MfAAAAJvx1aQ>: Info: msgid=<DM5PR1301MB218851999F4EAFE754276A07A8049@DM5PR1301MB2188.namprd13.prod.outlook.com>: saved mail to INBOX
Nov 15 08:22:48 lmtp(31): Info: Disconnect from 172.23.0.9: Client has quit the connection (state=READY)
